name: Build Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8.x'

      - name: Restore NuGet Packages
        run: nuget restore AtopPlugin.sln

      - name: Build Solution
        run: msbuild /p:Configuration=Release YourSolution.sln

      - name: Publish Application
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir=bin\Release\ AtopPlugin.csproj
